version: '3'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    build: .
    ports:
     - "3000:3000"
    links:
     - db 
    depends_on: 
     - db 
    volumes:
     - .:/cfcp
     - /cfcp/node_modules
  web:
    build: ./frontend
    ports:
     - "4200:4200"
    links:
     - db
     - api
    depends_on: 
     - db
     - api
    volumes:
     - ./frontend:/app
     - /app/node_modules